# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    # restart: always
    volumes:
      - calendso-data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - calendso-network
  calendso:
    build: .
    # restart: always
    ports:
      - 3000:3000
      - 5555:5555
    env_file: .env
    # depends_on:
    #   - db
    environment:
      - VIRTUAL_HOST=calendso.localhost
      - VIRTUAL_PORT=3000
    networks:
      - calendso-network
      - nginx-proxy
volumes:
  calendso-data:
networks:
  calendso-network:
    driver: bridge
  nginx-proxy:
    external: true
